/*
 * This source file was generated by the Gradle 'init' task
 */
package java_app;


import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class App {
    private JFrame frame;
    private JTextField inputField;
    private JTextArea outputArea;
    
    public String getGreeting() {
        return "Hello World!";
    }
    
    public void createAndShowGUI() {
        // Create and set up the window
        frame = new JFrame("My Java Application");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 400);
        frame.setLayout(new BorderLayout());
        
        // Create a panel for input components
        JPanel inputPanel = new JPanel();
        inputPanel.setLayout(new FlowLayout());
        
        // Add a label
        JLabel inputLabel = new JLabel("Enter text: ");
        inputPanel.add(inputLabel);
        
        // Add a text field
        inputField = new JTextField(20);
        inputPanel.add(inputField);
        
        // Add a button
        JButton submitButton = new JButton("Submit");
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                processInput();
            }
        });
        inputPanel.add(submitButton);
        
        // Add the input panel to the top of the frame
        frame.add(inputPanel, BorderLayout.NORTH);
        
        // Create a text area for output
        outputArea = new JTextArea();
        outputArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(outputArea);
        
        // Add the scroll pane to the center of the frame
        frame.add(scrollPane, BorderLayout.CENTER);
        
        // Display the window
        frame.setVisible(true);
    }
    
    private void processInput() {
        String input = inputField.getText();
        if (!input.isEmpty()) {
            outputArea.append("You entered: " + input + "\n");
            inputField.setText("");
        } else {
            outputArea.append("Please enter some text.\n");
        }
    }
    
    public static void main(String[] args) {
        // Use SwingUtilities to create and show GUI on the EDT
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                App app = new App();
                app.createAndShowGUI();
                
                // Display initial greeting in the output area
                app.outputArea.append(app.getGreeting() + "\n");
            }
        });
    }
}